name: ArenaManagement
main: com.fuzzycraft.ArenaManagement
version: 0.11

commands:
   ArenaManagement:
      description: ArenaManagement
      aliases: am
      permission: <plugin name>
      permission-message: You don't have permissions to use this command.