commands:
   basic:
      description: This is a demo command.
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   basic2:
      description: This is a demo command.
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>