name:  EventManager
main:  me.fuzzystatic.EventManager.EventManager
version:  1.00a
commands:
   em:
      description: Parent EventManager command.
      usage: |
        /emname [name]
        /emsave
        /emload
        /emsetcycle
        /emgetcycle
        /emsetentrance
        /emsetexit
        /emstart
        /emstop
        /emspawnamount [integer]
        /emspawncycle [seconds] 
        /emspawnisboss [true|false] 
        /emspawnlocation
        /emspawnmob [mob name]
        /emspawnname [name]
        /emspawnstart [seconds]
      permission: eventmanager.*
   emname:
      description: Select event. Will create event if event does not currently exist.
      permission: eventmanager.event.name
      usage: /emname [name]
   emsave:
      description: Save event location to a config and clipboard data to a schematic.
      permission: eventmanager.event.save
   emload:
      description: Load event from the schematic to the location specified in the config.
      permission: eventmanager.event.load
   emsetcycle:
      description: Set currently selected event cycle.
      permission: eventmanager.spawn.time
   emgetcycle:
      description: Get currently selected event cycle.
      permission: eventmanager.spawn.time
   emsetentrance:
      description: Set entrance of currently selected event.
      permission: eventmanager.event.entrance
   emsetexit:
      description: Set exit of currently selected event.
      permission: eventmanager.event.exit
   emstart:
      description: Start currently selected event.
      permission: eventmanager.event.start
   emstop:
      description: Stop all events.
      permission: eventmanager.event.stop
   emspawnamount:
      description: Set currently selected spawn amount.
      permission: eventmanager.spawn.amount
      usage: /emspawnamount [integer]
   emspawncycle:
      description: Set currently selected spawn cycle time.
      permission: eventmanager.spawn.cycle
      usage: /emspawncycle [long]
   emspawnisboss:
      description: Set currently selected spawn is boss feature.
      permission: eventmanager.spawn.isboss
      usage: /emspawnisboss [true|false]
   emspawnlocation:
      description: Set currently selected spawn location.
      permission: eventmanager.spawn.location
   emspawnmob:
      description: Set currently selected spawn mob.
      permission: eventmanager.spawn.mob
      usage: /emspawnmob [mob name]
   emspawnname:
      description: Select spawn. Will create spawn if spawn does not currently exist.
      permission: eventmanager.spawn.name
      usage: /emspawnmob [name]
   emspawnstart:
      description: Set currently selected spawn start time.
      permission: eventmanager.spawn.start
      usage: /emspawnstart [long]